# Default values for pgvector
replicaCount: 1

image:
  repository: tensorchord/pgvecto-rs 
  tag: pg14-v0.3.0 
  pullPolicy: IfNotPresent

postgresql:
  username: pguser 
  password: pgpass
  database: postgres
  port: 5432
  data_location: /bitnami/postgresql

persistence:
  enabled: true
  size: 16Gi
  storageClassName: ssd-storage 

service:
  type: ClusterIP
  port: 5432

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

